# Generated by Django 4.0 on 2022-03-22 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('gib', models.ImageField(default='default.png', upload_to='images')),
                ('price', models.CharField(max_length=255)),
                ('types', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=255)),
                ('modeltype', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('fbx', models.ImageField(default='default.png', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(max_length=225, null=True)),
                ('Purchase_date', models.DateField(blank=True, null=True)),
                ('modelname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pay_model', to='myapp.items')),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pay_price', to='myapp.items')),
            ],
        ),
    ]
