# Generated by Django 4.0 on 2022-03-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Purchase_date',
            new_name='date',
        ),
    ]
